# Generated by Django 4.0.6 on 2022-11-13 23:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monitoringStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=15, verbose_name='Ativos')),
                ('value_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Túnel máx.')),
                ('value_min', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001, 'Túnel míx. deve ser maior que R$ 0,00.')], verbose_name='Túnel mín.')),
                ('moniTime', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Periodicidade deve ser no mínimo de 1 hora.')], verbose_name='Tempo de checagem em horas')),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='historyMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=15, verbose_name='Código do ativo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(verbose_name='Data de atualização')),
                ('email', models.EmailField(max_length=255)),
                ('monistock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitorQuotes.monitoringstock')),
            ],
        ),
    ]
